---
deployment:
    tasks:
        - export DEPLOYPATH=/home/aleyosca/public_html/resurrexit/
        - export REPOPATH=/home/aleyosca/git/resurrexit/
        - /bin/rsync -a --delete ${REPOPATH}build/ ${DEPLOYPATH}
        - /bin/chmod 755 $DEPLOYPATH
        - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 '{}' \;
        - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 '{}' \;
