name: Create Release from Tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for creating releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history to access tags

      - name: Get tag name and message
        id: tag
        run: |
          TAG_NAME=${{ github.ref_name }}
          if [ -f .chglog/current-tag.md ]; then
            TAG_MESSAGE=$(cat .chglog/current-tag.md)
          else
            TAG_MESSAGE="Release $TAG_NAME"
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          # Use EOF delimiter for multiline tag message
          echo "tag_message<<EOF" >> $GITHUB_OUTPUT
          echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug Outputs
        run: |
          echo "Tag Name: ${{ steps.tag.outputs.tag_name }}"
          echo "Tag Message: ${{ steps.tag.outputs.tag_message }}"

      - name: Create GitHub Release
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tagName = '${{ steps.tag.outputs.tag_name }}';
            const tagMessage = '${{ steps.tag.outputs.tag_message }}';
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: tagName,
              body: tagMessage,
              draft: true,
              prerelease: false
            });
